site_name: MkDocs 中文站
site_url: https://mkdocs.cn
site_description: MkDocs使用、MkDocs安装、MkDocs配置介绍，MkDocs非官方中文站
site_author: MkDocs
repo_url: #
copyright: Copyright &copy; 2020 <a href="https://mkdocs.cn">MkDocs</a> | <a href="https://billing.virmach.com/aff.php?aff=6188&url=virmach.com/special-offers">Cheapest Hosting</a>.
#
theme:  #readthedocs

